dist: trusty
sudo: required
language: php

php:
  - 7.2

addons:
  chrome: stable

before install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  
install:
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - cp .env.travis .env
  - composer self-update
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - php artisan dusk

services:
  - mysql

# this will create a called testing if there is no database called testing
before_install:
  - mysql -e 'CREATE DATABASE testing;'
